kind: Deployment
apiVersion: apps/v1
metadata:
  name: counter-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-frontend
  template:
    metadata:
      labels:
        app: counter-frontend
    spec:
      containers:
        - name: coutner-frontend
          image: ghcr.io/rezopapi/counter-frontend:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
          - name: npm_config_cache
            value: ./.npm-cache
          - name: NODE_ENV
            value: production
          - name: BACKEND_URL
            valueFrom: 
              configMapKeyRef:
                name: counter-backend
                key: react_app_backend_url
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: counter-backend
  labels:
    app: counter-backend
data:
  react_app_backend_url: https://counter-backend-zlic-rbajra1.apps.exoscale-ch-gva-2-0.appuio.cloud
---
apiVersion: v1
kind: Service
metadata:
  name: counter-frontend
spec:
  selector:
    app: counter-frontend
  ports:
    - name: tcp-port
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: counter-frontend
  labels: 
    app: counter-frontend
spec:
  port:
    targetPort: tcp-port
  to:
    kind: Service
    name: counter-frontend
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: counter-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: counter-frontend
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80